#include <iostream>
#include <string>
#include <sstream>
#include <algorithm>

std::string input = R"(jpnomsle
                    wosinwfi
                    lekivkmf
                    ijymvkgq
                    bmwgxxrm
                    wctorbkj
                    iuktmcxm
                    xzufudbs
                    cwmsutoh
                    pcknfbys
                    yqjwprss
                    tyjpkbzw
                    smzvjevb
                    cvokjxwh
                    gpgcqtra
                    ddhfelaf
                    bbyfmepw
                    mkwbkugd
                    lipyfcji
                    whebvmly
                    fnfceaiv
                    lbiajtkz
                    odqbucmm
                    eytqacld
                    iswggugt
                    vsbeelal
                    qzuagiql
                    hwtibcxa
                    lpxfvhmo
                    pnwjlqsb
                    ksnntlgo
                    yjoizdcx
                    rtqwtjuk
                    ehrrryvq
                    aijkhibu
                    blzcoqqt
                    byxxkdzc
                    ptlkniqa
                    geolrsnl
                    ubhmuzjb
                    damdpnuu
                    smnjkopv
                    bvdfbuao
                    rserfaeg
                    dogngyha
                    xkzojucm
                    dfbqwprv
                    qwgvbjfw
                    mvpnizwm
                    wsampicy
                    yurbjmhm
                    drmgzhqp
                    dzianjpi
                    iresuphy
                    lxjrzrcv
                    ffjfzxdf
                    ssrddhnd
                    bvjefcmn
                    zqjhqrtl
                    uhgxmesn
                    nsziibek
                    acdgklky
                    niizwhfj
                    dengnljm
                    xmqszgyi
                    oufizqmt
                    ynhxyfva
                    qkwqtioc
                    todqskbu
                    zsluppbw
                    xvlbykhb
                    qgoeowcu
                    lvhwewll
                    uqexslyr
                    bgktzjzn
                    ldeojqqi
                    gismwlhy
                    htarpyss
                    oxetowsl
                    iymtvyia
                    rcsdusmz
                    nzwpiiqq
                    nwpubxxc
                    deifwrms
                    estasjvp
                    rustvine
                    iecvrvwv
                    ouwcaogn
                    kkapkike
                    sharidxa
                    vrypzuso
                    kdmuultn
                    tdwrwvyv
                    fotsbqly
                    exvncncx
                    rzmqqska
                    ozxpbjgl
                    bjztltqm
                    mmzjvdnm
                    wglezjrg
                    jpmoyhwg
                    gpggddnf
                    vpfwhqqa
                    qnjiebzb
                    xthftnad
                    sbdtwsii
                    vojgpucl
                    krvrizgn
                    xllmrooy
                    mahsrwam
                    qcakvhkt
                    fvwdvlty
                    fkdgbfzg
                    vobdysbi
                    kfmwpydn
                    citzswdp
                    iynphpar
                    myrtfvdj
                    tgnjmjgx
                    bfnuugyb
                    hxnjjiub
                    suutqaja
                    licsnpja
                    kfazyoho
                    yjdcddul
                    lfuzvuko
                    cueyfqoo
                    cgdrpadf
                    pqhwtazv
                    gfiuemfx
                    vexkkndk
                    hzfmwzvj
                    pjswysbs
                    gpqannoj
                    wlcpvvbs
                    tdsugdnd
                    juaaukem
                    obhsqpmf
                    ebzodoib
                    hlgkjsof
                    rhdpftoc
                    tvkdgreo
                    knuacdvw
                    rutjaaze
                    hlapqcfu
                    eermrtme
                    kfsztndj
                    qjwclbif
                    axlrkqiz
                    pgozhccw
                    ufytusig
                    gdskhtzb
                    wdpwtqji
                    pfgzsxvn
                    bamiwews
                    enkfycps
                    dsglfyyz
                    arizzkcw
                    fyirvhby
                    igjyhvbi
                    bavypopm
                    fqudvrdi
                    gepouvac
                    ugbwodrp
                    hclwxxun
                    ncnlgwds
                    fvnaifxa
                    xtzfppwj
                    viekslmh
                    lksqojwk
                    xnlihitg
                    vxmlnoci
                    ccsmdidh
                    oqrtyvkz
                    urzmcqmj
                    qbnkluys
                    nvdazrnu
                    zvywgxdn
                    scugbiox
                    ewivhegg
                    yfyexsfs
                    kgocfzja
                    zrjdaqta
                    gkhpnanf
                    vlxjhfjt
                    ykgbopmt
                    utiesnih
                    shakguot
                    hywmcuku
                    gjltpbfr
                    lzkatxwc
                    wxieyztu
                    iwvtqbeh
                    tlcqcsjl
                    fuxqnppn
                    ouoernej
                    xfdtewzd
                    etoaplbw
                    secuzkdr
                    kclibqre
                    qooqiobq
                    nrcfwxfi
                    maqnntic
                    qwpulgbj
                    pdjzfvyj
                    iwqhwlnj
                    oihftklw
                    iywvbexe
                    rhpzloag
                    leaelzup
                    hlggwpor
                    pqehtxul
                    zkyaybep
                    gheivvpk
                    xqlgyrlb
                    wujztjtt
                    nrwxkmkd
                    ijtcaoux
                    tmmjmpeh
                    xdhdcytk
                    jpchdagy
                    qlfdefaw
                    emshcltx
                    prhmorgz
                    dhdxxubc
                    ntfmmmax
                    oxzaksof
                    zonxcmwn
                    njpytedo
                    fftomgwl
                    gzlvtohn
                    hyibhnja
                    irxwinpr
                    vojbajhr
                    kqgydtiq
                    pufiemmt
                    mvkqthft
                    xbjrglza
                    rrdlpzqy
                    gmayqdny
                    moykjapv
                    fcfzqmnq
                    hwcvctfe
                    aerljjio
                    ydvqdfym
                    vobhfewn
                    fvfcoohl
                    chqjnmcq
                    geupmbzm
                    bekjwcaz
                    olujcecy
                    tlmygzkv
                    mhgjxuvt
                    lwnjsqcu
                    yjoncnil
                    vbfhqdlb
                    gkrhryeh
                    cdofkbpu
                    jubtekng
                    azzixhzy
                    zgsskveh
                    ygxbbpgm
                    ntvepwno
                    uaivckks
                    kpcoypio
                    elfhilea
                    qofoadkv
                    cetmbhlm
                    cdqiheur
                    bopfgmrd
                    ioircgxh
                    znlyvzrq
                    nhsuqzst
                    hxizhcye
                    jktpxqxg
                    mrhhzqpq
                    phzlffwd
                    zfyipddp
                    ixwlukmz
                    uzmznxgp
                    bizkzxfx
                    gabulwor
                    jmguhjti
                    yzrbgcvy
                    waranxrq
                    otilexwt
                    ecwupxiv
                    rzdcomik
                    qkbgxhjv
                    dwkuiczc
                    jxghaqdc
                    srocreym
                    sxhgoexu
                    fghwatip
                    czdccopz
                    oiuyqhsh
                    ctxsjzlb
                    tlifjaof
                    uvgumrre
                    uneknsqz
                    oxkcxoqh
                    bypdayvx
                    agdrkwty
                    enuoyago
                    zowyrehd
                    moxjokhp
                    llsdktgq
                    ofccwfdq
                    betygaxh
                    ypcqavic
                    dppvquxj
                    qtfjgzrm
                    hyuatorj
                    utannehg
                    njylrfzo
                    azbhxjtg
                    flgkqfgk
                    rmimpbmd
                    lucexbnt
                    hrxujuba
                    cmymrpiv
                    tnwoqgyf
                    oovhrncn
                    zsbxhvpv
                    ywqfdmvv
                    lsfufyus
                    syqsyyyq
                    oxuqqgqz
                    dvmqxgyw
                    vkvvovci
                    jhzqcwsd
                    oamvebre
                    qncykjpp
                    kkxhndot
                    tzcxiwwt
                    dbmxcvlx
                    anexktve
                    axrssdyc
                    buwcouzt
                    ddtvfdeq
                    cgttxyuc
                    ilbidgtr
                    rfndwckv
                    bstpsmkx
                    cbzvrfnk
                    qjaqwbyi
                    vcpchkwk
                    vaapmcrf
                    xpbfarcg
                    nakawsui
                    wfyiwmpb
                    wbkxtkhc
                    mjigbbbf
                    sjdgahss
                    ahtdkgbu
                    dineiyik
                    soahqthe
                    ptmlrfaa
                    nfewoxxr
                    atgghurm
                    ulspehpz
                    hqzumvcm
                    vahbjujo
                    emrmchfj
                    ulfxsmod
                    bqoaxtvw
                    jfklxtsd
                    vyqmyqlr
                    dqoqtmvt
                    lgbzegrj
                    hicyyfjf
                    keagysmb
                    uanpokzr
                    pmmdayzv
                    aagsbnrn
                    jqwianxu
                    mivxziox
                    hyfwolyx
                    tdxjcoye
                    prlslumt
                    xnlljwjt
                    qfzbgzqr
                    wszgyzga
                    tpupozsc
                    vxhwkloy
                    pvrbtcdq
                    rjeeizwo
                    fevnqnvi
                    miqxseme
                    qrneqrxe
                    yzomhybx
                    tplrffhp
                    evxcbwvg
                    qhhxylde
                    kvzxublx
                    aaycljrc
                    fdonlrel
                    rswdadys
                    elpfzlgl
                    tbcppggi
                    bulqfhyu
                    ewbzhrqv
                    wwepirtw
                    ugazsxlk
                    xaalxyhv
                    imddfsvc
                    lszgvama
                    xzgwdixv
                    neukxolf
                    fmfvjylf
                    rxrcgmjg
                    gysmaadp
                    zankjgys
                    amefwpuh
                    scotnyzl
                    ssakungx
                    sakfzaud
                    dgdnjmjt
                    uyhdxrvl
                    ydhbtxah
                    chezbkhz
                    wjnyjuzk
                    kxvujbpw
                    igrjmhcm
                    gublnlvh
                    vjfrwqwg
                    oprvwhfr
                    yilyvzez
                    yhodibug
                    fivsekbb
                    cmlomgem
                    rpiomxuq
                    kaxjtsfg
                    fmfsffjr
                    wddxezfa
                    wcrligql
                    bnrohvbd
                    msprlord
                    rjyomeck
                    aigiqhns
                    nnjszkjz
                    kpdcrcuq
                    znuwpnsw
                    awservpq
                    mhbgizrc
                    gcqxiazq
                    ezpemwef
                    abvtqswk
                    zyvkkqap
                    pnyybtke
                    kqglepvn
                    lsxronqx
                    eccaqkln
                    jitacsjj
                    dibwyvne
                    achslqlr
                    zaocguqz
                    hrvktaun
                    desabwmb
                    ztmvhatf
                    qvsbgobs
                    xplhpigo
                    mnvoixgz
                    hbwwscfx
                    mbjbotfb
                    ycbeojag
                    uwqqlzse
                    gffufrdj
                    qhpjrmbw
                    fkprueel
                    ctenlqry
                    dqtrrffp
                    sweaftmd
                    yekzdapr
                    zyskkvsp
                    cjwysyjp
                    vphuswhl
                    tzbjniju
                    wvmxhrzk
                    vsyedbwh
                    uxllegxv
                    jginldku
                    jdczunlb
                    jgdruatz
                    makhdcsq
                    wexgoeax
                    squsatpz
                    cqubtkni
                    xrnfofvh
                    miuvlese
                    aefylred
                    fusyuybs
                    bykemjhu
                    aasrsjxf
                    ykvdmwxd
                    joyoibnb
                    tpoowkug
                    jnthvfhc
                    sxxfyiwb
                    ksqmggsz
                    ymjiliqp
                    uwcnppas
                    flakidlb
                    ikchcehd
                    ptatwguk
                    pmolarwq
                    snehzsaw
                    wwqmvmwy
                    ulvijwso
                    jbvgdeqk
                    xkkodsar
                    yvbtdfxu
                    hcpylcfh
                    xgxzfvkw
                    zlklsmdi
                    obrqupcw
                    ibkyzfoh
                    tqvvdgps
                    kzynbdif
                    ztjnvwsu
                    xksqgpqu
                    uwlpugoh
                    pdzhciob
                    kujijtjj
                    jvencltk
                    qozxxgkg
                    eoasncao
                    gpunvjky
                    ijqnioni
                    nsjpbqik
                    ttyrgxuc
                    nzxunpqn
                    rknbznol
                    wbmorrtq
                    tpfhbxfp
                    lxdjaykw
                    riubeihx
                    hrbbmbky
                    atjnsacd
                    xtekdptu
                    rdtevcyh
                    cjpssjvp
                    cjywepqo
                    rutbqeuw
                    sdbxunzj
                    ekpvsftr
                    obutdocz
                    jwcpzflw
                    lqcnhser
                    lhojehdt
                    gfrnfmxx
                    jyxwltij
                    pupdxhxy
                    oqqbpjrn
                    zmrobltk
                    rhkvdyec
                    nrvsnrtc
                    pmpmdixu
                    hwqzyvef
                    tcnckoov
                    icgvlwso
                    nqiaause
                    jntduaap
                    timsxgui
                    dqvlekla
                    zkxemsmj
                    zbquxifp
                    mgyvaneg
                    eoqtkvpo
                    wxyqshnk
                    vritmuaz
                    nzqlrzfn)";

using Alphabet = std::vector<std::pair<char, int>>;
using Alphabets = std::vector<Alphabet>;

void removeSpaces(std::string & p_input)
{
    p_input.erase(remove_if(p_input.begin(), p_input.end(), isspace), p_input.end());
}

Alphabets prepareAlphabetVectors(int p_size)
{
    Alphabet l_alphabet;
    for(char i = 'a'; i <= 'z'; i++)
    {
        l_alphabet.push_back(std::make_pair(i, 0));
    }
    return Alphabets(p_size, l_alphabet);
}

void calculateNumberOfChars(Alphabets & p_alphabets)
{
    std::string l_item(input);
    for(auto x = 0; x < l_item.size(); x+=8)
    {
        for(auto i = x; i < x+8; i++)
        {
            auto l_alphabetIt = std::find_if(p_alphabets[i%8].begin(), p_alphabets[i%8].end(), [&i, &x, &l_item](const auto & p_pair)
            {
                return l_item[i] == p_pair.first;
            });
            (*l_alphabetIt).second++;
        }
    }
}

std::string getMostFrequentChar(const Alphabets & p_alphabets)
{
    std::string l_result;
    std::string l_singleChar;
    for (const auto & alphabets : p_alphabets)
    {
        int l_min = 10000;
        for (const auto & alphabet : alphabets)
        {
            if (alphabet.second < l_min)
            {
                l_min = alphabet.second;
                l_singleChar = alphabet.first;
            }
        }
        l_result += l_singleChar;
    }
    return l_result;
}

int main()
{
    removeSpaces(input);
    Alphabets l_alphabets = prepareAlphabetVectors(8);
    calculateNumberOfChars(l_alphabets);

    std::cout << "Password = " << getMostFrequentChar(l_alphabets) << std::endl;

    return 0;
}
